import tensorflow as tf
from tensorflow.python.ops import tensor_array_ops, control_flow_ops
import numpy as np


class ROLLOUT(object):
    def __init__(self, lstm, update_rate):
        self.lstm = lstm
        self.update_rate = update_rate

        self.num_emb = self.lstm.num_emb
        self.batch_size = self.lstm.batch_size
        self.emb_dim = self.lstm.emb_dim
        self.hidden_dim = self.lstm.hidden_dim
        self.sequence_length = self.lstm.sequence_length
        self.start_token = tf.identity(self.lstm.start_token)
        self.dropout_keep_prob = self.lstm.dropout_keep_prob
        self.num_recurrent_layers = self.lstm.num_recurrent_layers

        self.g_embeddings = tf.identity(self.lstm.g_embeddings)

        self.g_recurrent_unit = [self.create_recurrent_unit(i) for i in range(self.num_recurrent_layers)] # maps h_tm1 to h_t for generator
        self.g_output_unit = self.create_output_unit()  # maps h_t to o_t (output token logits)

        #####################################################################################################
        # placeholder definition
        self.x = tf.placeholder(tf.int32, shape=[self.batch_size, self.sequence_length]) # sequence of tokens generated by generator
        self.given_num = tf.placeholder(tf.int32)

        # processed for batch
        with tf.device("/cpu:0"):
            self.processed_x = tf.transpose(tf.nn.embedding_lookup(self.g_embeddings, self.x), perm=[1, 0, 2])  # seq_length x batch_size x emb_dim

        ta_emb_x = tensor_array_ops.TensorArray(
            dtype=tf.float32, size=self.sequence_length)
        ta_emb_x = ta_emb_x.unstack(self.processed_x)

        ta_x = tensor_array_ops.TensorArray(dtype=tf.int32, size=self.sequence_length)
        ta_x = ta_x.unstack(tf.transpose(self.x, perm=[1, 0]))
        #####################################################################################################

        self.h0 = tf.zeros([self.batch_size, self.hidden_dim])
        self.h0 = [tf.stack([self.h0, self.h0])] * self.num_recurrent_layers

        gen_x = tensor_array_ops.TensorArray(dtype=tf.int32, size=self.sequence_length,
                                             dynamic_size=False, infer_shape=True)

        # When current index i < given_num, use the provided tokens as the input at each time step
        def _g_recurrence_1(i, x_t, h_tm1, given_num, gen_x):
            # h_t = self.g_recurrent_unit(x_t, h_tm1)  # hidden_memory_tuple
            h_t = []
            curr_x = x_t
            for layer_i in range(self.num_recurrent_layers):
                h_t.append(self.g_recurrent_unit[layer_i](curr_x, h_tm1[layer_i]))  # hidden_memory_tuple
                curr_hidden_state, curr_prev = tf.unstack(h_t[-1])
                curr_x = curr_hidden_state
            x_tp1 = ta_emb_x.read(i)


            gen_x = gen_x.write(i, ta_x.read(i))
            return i + 1, x_tp1, h_t, given_num, gen_x

        # When current index i >= given_num, start roll-out, use the output as time step t as the input at time step t+1
        def _g_recurrence_2(i, x_t, h_tm1, given_num, gen_x):
            # h_t = self.g_recurrent_unit(x_t, h_tm1)  # hidden_memory_tuple
            # o_t = self.g_output_unit(h_t)  # batch x vocab , logits not prob
            h_t = []
            curr_x = x_t
            for layer_i in range(self.num_recurrent_layers):
                h_t.append(self.g_recurrent_unit[layer_i](curr_x, h_tm1[layer_i]))  # hidden_memory_tuple
                curr_hidden_state, curr_prev = tf.unstack(h_t[-1])
                curr_x = curr_hidden_state
            o_t = self.g_output_unit(h_t[-1])
            log_prob = tf.log(tf.nn.softmax(o_t))
            next_token = tf.cast(tf.reshape(tf.multinomial(log_prob, 1), [self.batch_size]), tf.int32)
            x_tp1 = tf.nn.embedding_lookup(self.g_embeddings, next_token)  # batch x emb_dim
            gen_x = gen_x.write(i, next_token)  # indices, batch_size
            return i + 1, x_tp1, h_t, given_num, gen_x

        i, x_t, h_tm1, given_num, self.gen_x = control_flow_ops.while_loop(
            cond=lambda i, _1, _2, given_num, _4: i < given_num,
            body=_g_recurrence_1,
            loop_vars=(tf.constant(0, dtype=tf.int32),
                       tf.nn.embedding_lookup(self.g_embeddings, self.start_token), self.h0, self.given_num, gen_x))

        _, _, _, _, self.gen_x = control_flow_ops.while_loop(
            cond=lambda i, _1, _2, _3, _4: i < self.sequence_length,
            body=_g_recurrence_2,
            loop_vars=(i, x_t, h_tm1, given_num, self.gen_x))

        self.gen_x = self.gen_x.stack()  # seq_length x batch_size
        self.gen_x = tf.transpose(self.gen_x, perm=[1, 0])  # batch_size x seq_length

    def get_reward(self, sess, input_x, rollout_num, discriminator):
        rewards = []
        for i in range(rollout_num):
            # given_num between 1 to sequence_length - 1 for a part completed sentence
            for given_num in range(1, self.sequence_length ):
                feed = {self.x: input_x, self.given_num: given_num}
                samples = sess.run(self.gen_x, feed)
                feed = {discriminator.input_x: samples, discriminator.dropout_keep_prob: 1.0}
                ypred_for_auc = sess.run(discriminator.ypred_for_auc, feed)
                ypred = np.array([item[1] for item in ypred_for_auc])
                if i == 0:
                    rewards.append(ypred)
                else:
                    rewards[given_num - 1] += ypred

            # the last token reward
            feed = {discriminator.input_x: input_x, discriminator.dropout_keep_prob: 1.0}
            ypred_for_auc = sess.run(discriminator.ypred_for_auc, feed)
            ypred = np.array([item[1] for item in ypred_for_auc])
            if i == 0:
                rewards.append(ypred)
            else:
                # completed sentence reward
                rewards[self.sequence_length - 1] += ypred

        rewards = np.transpose(np.array(rewards)) / (1.0 * rollout_num)  # batch_size x seq_length
        return rewards

    def create_recurrent_unit(self, num):

        if num == 0:
            self.Wi = [None] * self.num_recurrent_layers
            self.Ui = [None] * self.num_recurrent_layers
            self.bi = [None] * self.num_recurrent_layers
            self.Wf = [None] * self.num_recurrent_layers
            self.Uf = [None] * self.num_recurrent_layers
            self.bf = [None] * self.num_recurrent_layers
            self.Wog = [None] * self.num_recurrent_layers
            self.Uog = [None] * self.num_recurrent_layers
            self.bog = [None] * self.num_recurrent_layers
            self.Wc = [None] * self.num_recurrent_layers
            self.Uc = [None] * self.num_recurrent_layers
            self.bc = [None] * self.num_recurrent_layers

        # Weights and Bias for input and hidden tensor
        self.Wi[num] = tf.identity(self.lstm.Wi[num])
        self.Ui[num] = tf.identity(self.lstm.Ui[num])
        self.bi[num] = tf.identity(self.lstm.bi[num])

        self.Wf[num] = tf.identity(self.lstm.Wf[num])
        self.Uf[num] = tf.identity(self.lstm.Uf[num])
        self.bf[num] = tf.identity(self.lstm.bf[num])

        self.Wog[num] = tf.identity(self.lstm.Wog[num])
        self.Uog[num] = tf.identity(self.lstm.Uog[num])
        self.bog[num] = tf.identity(self.lstm.bog[num])

        self.Wc[num] = tf.identity(self.lstm.Wc[num])
        self.Uc[num] = tf.identity(self.lstm.Uc[num])
        self.bc[num] = tf.identity(self.lstm.bc[num])

        def unit(x, hidden_memory_tm1):
            previous_hidden_state, c_prev = tf.unstack(hidden_memory_tm1)

            # Input Gate
            i = tf.sigmoid(
                tf.matmul(x, self.Wi[num]) +
                tf.matmul(previous_hidden_state, self.Ui[num]) + self.bi[num]
            )

            # Forget Gate
            f = tf.sigmoid(
                tf.matmul(x, self.Wf[num]) +
                tf.matmul(previous_hidden_state, self.Uf[num]) + self.bf[num]
            )

            # Output Gate
            o = tf.sigmoid(
                tf.matmul(x, self.Wog[num]) +
                tf.matmul(previous_hidden_state, self.Uog[num]) + self.bog[num]
            )

            # New Memory Cell
            c_ = tf.nn.tanh(
                tf.matmul(x, self.Wc[num]) +
                tf.matmul(previous_hidden_state, self.Uc[num]) + self.bc[num]
            )

            # Final Memory cell
            c = f * c_prev + i * c_

            # Current Hidden state
            current_hidden_state = o * tf.nn.tanh(c)

            return tf.stack([current_hidden_state, c])

        return unit

    def update_recurrent_unit(self,num):
        # Weights and Bias for input and hidden tensor
        self.Wi[num] = self.update_rate * self.Wi[num] + (1 - self.update_rate) * tf.identity(self.lstm.Wi[num])
        self.Ui[num] = self.update_rate * self.Ui[num] + (1 - self.update_rate) * tf.identity(self.lstm.Ui[num])
        self.bi[num] = self.update_rate * self.bi[num] + (1 - self.update_rate) * tf.identity(self.lstm.bi[num])

        self.Wf[num] = self.update_rate * self.Wf[num] + (1 - self.update_rate) * tf.identity(self.lstm.Wf[num])
        self.Uf[num] = self.update_rate * self.Uf[num] + (1 - self.update_rate) * tf.identity(self.lstm.Uf[num])
        self.bf[num] = self.update_rate * self.bf[num] + (1 - self.update_rate) * tf.identity(self.lstm.bf[num])

        self.Wog[num] = self.update_rate * self.Wog[num] + (1 - self.update_rate) * tf.identity(self.lstm.Wog[num])
        self.Uog[num] = self.update_rate * self.Uog[num] + (1 - self.update_rate) * tf.identity(self.lstm.Uog[num])
        self.bog[num] = self.update_rate * self.bog[num] + (1 - self.update_rate) * tf.identity(self.lstm.bog[num])

        self.Wc[num] = self.update_rate * self.Wc[num] + (1 - self.update_rate) * tf.identity(self.lstm.Wc[num])
        self.Uc[num] = self.update_rate * self.Uc[num] + (1 - self.update_rate) * tf.identity(self.lstm.Uc[num])
        self.bc[num] = self.update_rate * self.bc[num] + (1 - self.update_rate) * tf.identity(self.lstm.bc[num])

        def unit(x, hidden_memory_tm1):
            previous_hidden_state, c_prev = tf.unstack(hidden_memory_tm1)

            # Input Gate
            i = tf.sigmoid(
                tf.matmul(x, self.Wi[num]) +
                tf.matmul(previous_hidden_state, self.Ui[num]) + self.bi[num]
            )

            # Forget Gate
            f = tf.sigmoid(
                tf.matmul(x, self.Wf[num]) +
                tf.matmul(previous_hidden_state, self.Uf[num]) + self.bf[num]
            )

            # Output Gate
            o = tf.sigmoid(
                tf.matmul(x, self.Wog[num]) +
                tf.matmul(previous_hidden_state, self.Uog[num]) + self.bog[num]
            )

            # New Memory Cell
            c_ = tf.nn.tanh(
                tf.matmul(x, self.Wc[num]) +
                tf.matmul(previous_hidden_state, self.Uc[num]) + self.bc[num]
            )

            # Final Memory cell
            c = f * c_prev + i * c_

            # Current Hidden state
            current_hidden_state = o * tf.nn.tanh(c)

            return tf.stack([current_hidden_state, c])

        return unit

    def create_output_unit(self):
        self.Wo = tf.identity(self.lstm.Wo)
        self.bo = tf.identity(self.lstm.bo)

        def unit(hidden_memory_tuple):
            hidden_state, c_prev = tf.unstack(hidden_memory_tuple)
            # hidden_state : batch x hidden_dim
            logits = tf.matmul(hidden_state, self.Wo) + self.bo
            # output = tf.nn.softmax(logits)
            return logits

        return unit

    def update_output_unit(self):
        self.Wo = self.update_rate * self.Wo + (1 - self.update_rate) * tf.identity(self.lstm.Wo)
        self.bo = self.update_rate * self.bo + (1 - self.update_rate) * tf.identity(self.lstm.bo)

        def unit(hidden_memory_tuple):
            hidden_state, c_prev = tf.unstack(hidden_memory_tuple)
            # hidden_state : batch x hidden_dim
            logits = tf.matmul(hidden_state, self.Wo) + self.bo
            # output = tf.nn.softmax(logits)
            return logits

        return unit

    def update_params(self):
        self.g_embeddings = tf.identity(self.lstm.g_embeddings)
        self.g_recurrent_unit = [self.update_recurrent_unit(i) for i in range(self.num_recurrent_layers)]
        self.g_output_unit = self.update_output_unit()
